//create a district filter to help users navigate
import React, { Component } from 'react';
import ReactBootstrap, { Button, Panel, NavItem, NavDropdown, MenuItem, Dropdown, DropdownButton } from 'react-bootstrap';

//generate a Bootsrap sidebar, with menu items generated by the SidebarItem component
class DistrictFilter extends Component {
  constructor(...args) {
    super(...args);
    this.state = {
      saco: true,
      androscoggin: true,
      pemigewasset: true
    };
  }
  componentDidUpdate() {
    //create bounds object to store bounds data and update map
    var bounds;

    //detect state  and toggle css
    if (this.state.saco == true) {
        $("#saco").css("background-color","rgba(57, 132, 57, 0.5)");
    } else {
        $("#saco").css("background-color", "#252525")   
    }; 
    if (this.state.androscoggin == true) {
         $("#androscoggin").css("background-color","rgba(57, 132, 57, 0.5)");
    } else {
        $("#androscoggin").css("background-color", "#252525")   
    };
    if (this.state.pemigewasset == true) {
         $("#pemigewasset").css("background-color","rgba(57, 132, 57, 0.5)");
    } else {
        $("#pemigewasset").css("background-color", "#252525")   
    };

    //TODO load map element and its layer to get bounds data?
  }
  render() {
    return(
      <div id="district-filter-wrapper">
        <Button id="androscoggin" bsStyle="success" onClick={ ()=> this.setState({ androscoggin: !this.state.androscoggin })}>Androscoggin District</Button>
        <Button id="pemigewasset" bsStyle="success" onClick={ ()=> this.setState({ pemigewasset: !this.state.pemigewasset })}>Pemigewasset District</Button>
        <Button id="saco" bsStyle="success" onClick={ ()=> this.setState({ saco: !this.state.saco })}>Saco District</Button>
      </div>
    );
  }
};

export default DistrictFilter;