import React, { Component } from 'react';
import SidebarItem from './SidebarItem';
import ReactBootstrap, { Button, Panel } from 'react-bootstrap';

//generate a Bootsrap sidebar, with menu items generated by the SidebarItem component
class Sidebar extends Component {
  constructor(...args) {
    super(...args);
    this.state = {
      openHiking: true,
      openRecreation: false,
      openLodging: false,
      openAmenities: false,
      openSafety: false,
      openNatural: false
    };
  }
  render() {
    return(
      <div id="sidebar-wrapper">
        <ul id="sidebar-menu" className="sidebar-nav">
            <li className="sidebar-brand"><a id="menu-toggle" href="#">Layers<span id="main-icon1" className="glyphicon glyphicon-triangle-right"></span><span id="main-icon2" className="glyphicon glyphicon-triangle-left"></span></a></li>
        </ul>
        <ul className="sidebar-nav" id="sidebar">
          <Button bsStyle="success" onClick={ ()=> this.setState({ openHiking: !this.state.openHiking })}>Hiking<span className="caret"></span></Button>
          <Panel collapsible expanded={this.state.openHiking}>
            <SidebarItem eventKey="1-1" text="Trailhead" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142851hiking.svg"/>
            <SidebarItem eventKey="1-2" text="Hiking Trail" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142838trail.svg" />
            <SidebarItem eventKey="1-3" text="AMC Hut" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/building-18.svg"/>
            <SidebarItem eventKey="1-4" text="Shelter" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710164913shelter-15.svg"/>
            <SidebarItem eventKey="1-5" text="Tentsite" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/triangle-stroked-18.svg"/>
          </Panel>
          <Button bsStyle="success" onClick={ ()=> this.setState({ openRecreation: !this.state.openRecreation })}>Recreation<span className="caret"></span></Button>
          <Panel collapsible expanded={this.state.openRecreation}>
            <SidebarItem eventKey="2-1" text="Boating" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142826canoe.svg"/>
            <SidebarItem eventKey="2-2" text="Nordic Skiing" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712143226nordic.svg"/>          
            <SidebarItem eventKey="2-3" text="Alpine Skiing" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/skiing-18.svg"/>          
          </Panel>
          <Button bsStyle="success" onClick={ ()=> this.setState({ openLodging: !this.state.openLodging })}>Lodging<span className="caret"></span></Button>
          <Panel collapsible expanded={this.state.openLodging}>
            <SidebarItem eventKey="3-1" text="Family Camping" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/campsite-18.svg"/>
            <SidebarItem eventKey="3-2" text="Group Camping" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142832groupcamp.svg"/>
            <SidebarItem eventKey="3-3" text="Lodge" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/town-18.svg"/>
          </Panel>
          <Button bsStyle="success" onClick={ ()=> this.setState({ openAmenities: !this.state.openAmenities })}>Roadside Amenities<span className="caret"></span></Button>
          <Panel collapsible expanded={this.state.openAmenities}>
            <SidebarItem eventKey="4-1" text="Picnic" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710165514picnic-site-15.svg"/>
            <SidebarItem eventKey="4-2" text="Observation" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710162834observation.svg"/>
            <SidebarItem eventKey="4-3" text="Information" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710160800information-15.svg"/>
          </Panel>  
          <Button bsStyle="success" onClick={ ()=> this.setState({ openSafety: !this.state.openSafety })}>Safety<span className="caret"></span></Button>
          <Panel collapsible expanded={this.state.openSafety}>
            <SidebarItem eventKey="5-1" text="Fire Station" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/fire-station-18.svg"/>
            <SidebarItem eventKey="5-2" text="Fire Tower" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710165259firetower.svg"/>
          </Panel>             
          <Button bsStyle="success" onClick={ ()=> this.setState({ openNatural: !this.state.openNatural })}>Natural Features<span className="caret"></span></Button>
          <Panel collapsible expanded={this.state.openNatural}>
            <SidebarItem eventKey="6-1" text="Mountains" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710172003mountain-15.svg"/>
            <SidebarItem eventKey="6-2" text="Forest" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712164429forest.svg"/>
          </Panel>
        </ul>
      </div>
    );
  }
};

export default Sidebar;