import React, { Component } from 'react';
import SidebarItem from './SidebarItem';
import ReactBootstrap, { NavItem, NavDropdown, MenuItem, Dropdown, DropdownButton } from 'react-bootstrap';

//generate a Bootsrap sidebar, with menu items generated by the SidebarItem component
class Sidebar extends Component {
  render() {
    return(
      <div id="sidebar-wrapper">
        <ul id="sidebar-menu" className="sidebar-nav">
            <li className="sidebar-brand"><a id="menu-toggle" href="#">Layers<span id="main-icon1" className="glyphicon glyphicon-triangle-right"></span><span id="main-icon2" className="glyphicon glyphicon-triangle-left"></span></a></li>
        </ul>
        <ul className="sidebar-nav" id="sidebar">     
          <SidebarItem eventKey="1" text="Mountains" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710172003mountain-15.svg"/>
          <SidebarItem eventKey="2" text="Trails" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142838trail.svg" />
          <NavDropdown eventKey="3" title="Recreation" id="recreation-dropdown">
            <SidebarItem eventKey="3.1" text="Information" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710160800information-15.svg"/>
            <SidebarItem eventKey="3.2" text="Picnic" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710165514picnic-site-15.svg"/>
            <SidebarItem eventKey="3.3" text="Observation" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710162834observation.svg"/>
            <SidebarItem eventKey="3.4" text="Trailhead" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142851hiking.svg"/>
            <SidebarItem eventKey="3.5" text="Boating" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142826canoe.svg"/>
            <SidebarItem eventKey="3.6" text="Alpine Skiing" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/skiing-18.svg"/>
            <SidebarItem eventKey="3.7" text="Nordic Skiing" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712143226nordic.svg"/>
            <SidebarItem eventKey="3.8" text="AMC Hut / Lodge" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/building-18.svg"/>
            <SidebarItem eventKey="3.9" text="Rental Cabin" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/building-18.svg"/>
            <SidebarItem eventKey="3.10" text="Camping" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/campsite-18.svg"/>
            <SidebarItem eventKey="3.11" text="Group Camping" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712142832groupcamp.svg"/>
            <SidebarItem eventKey="3.12" text="Shelter" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710164913shelter-15.svg"/>
            <SidebarItem eventKey="3.13" text="Tentsite" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710164921campsite-11.svg"/>
            <SidebarItem eventKey="3.14" text="Fire Tower" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170710165259firetower.svg"/>
          </NavDropdown>
          <SidebarItem eventKey="4" text="Forest" url="https://s3.amazonaws.com/com.cartodb.users-assets.production/production/bachmansande/assets/20170712164429forest.svg"/>
        </ul>
      </div>
    );
  }
};

export default Sidebar;